package com.sh.drools.dal.model;

import java.util.Date;

public class Attachment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_attachment.ID
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_attachment.CONTENT_TYPE
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    private String contentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_attachment.FILE_PATH
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_attachment.FILE_SIZE
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    private Integer fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_attachment.ORIGINAL_NAME
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    private String originalName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_attachment.SUFFIX
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    private String suffix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_attachment.ATT_TYPE
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    private String attType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_attachment.UPLOAD_TIME
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_attachment.MEMBER_ID
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    private Integer memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_attachment.value1
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    private String value1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_attachment.value2
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    private String value2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_attachment.ID
     *
     * @return the value of crm_attachment.ID
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_attachment.ID
     *
     * @param id the value for crm_attachment.ID
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_attachment.CONTENT_TYPE
     *
     * @return the value of crm_attachment.CONTENT_TYPE
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_attachment.CONTENT_TYPE
     *
     * @param contentType the value for crm_attachment.CONTENT_TYPE
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public void setContentType(String contentType) {
        this.contentType = contentType == null ? null : contentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_attachment.FILE_PATH
     *
     * @return the value of crm_attachment.FILE_PATH
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_attachment.FILE_PATH
     *
     * @param filePath the value for crm_attachment.FILE_PATH
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_attachment.FILE_SIZE
     *
     * @return the value of crm_attachment.FILE_SIZE
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public Integer getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_attachment.FILE_SIZE
     *
     * @param fileSize the value for crm_attachment.FILE_SIZE
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public void setFileSize(Integer fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_attachment.ORIGINAL_NAME
     *
     * @return the value of crm_attachment.ORIGINAL_NAME
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public String getOriginalName() {
        return originalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_attachment.ORIGINAL_NAME
     *
     * @param originalName the value for crm_attachment.ORIGINAL_NAME
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public void setOriginalName(String originalName) {
        this.originalName = originalName == null ? null : originalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_attachment.SUFFIX
     *
     * @return the value of crm_attachment.SUFFIX
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_attachment.SUFFIX
     *
     * @param suffix the value for crm_attachment.SUFFIX
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public void setSuffix(String suffix) {
        this.suffix = suffix == null ? null : suffix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_attachment.ATT_TYPE
     *
     * @return the value of crm_attachment.ATT_TYPE
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public String getAttType() {
        return attType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_attachment.ATT_TYPE
     *
     * @param attType the value for crm_attachment.ATT_TYPE
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public void setAttType(String attType) {
        this.attType = attType == null ? null : attType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_attachment.UPLOAD_TIME
     *
     * @return the value of crm_attachment.UPLOAD_TIME
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_attachment.UPLOAD_TIME
     *
     * @param uploadTime the value for crm_attachment.UPLOAD_TIME
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_attachment.MEMBER_ID
     *
     * @return the value of crm_attachment.MEMBER_ID
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_attachment.MEMBER_ID
     *
     * @param memberId the value for crm_attachment.MEMBER_ID
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_attachment.value1
     *
     * @return the value of crm_attachment.value1
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public String getValue1() {
        return value1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_attachment.value1
     *
     * @param value1 the value for crm_attachment.value1
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public void setValue1(String value1) {
        this.value1 = value1 == null ? null : value1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_attachment.value2
     *
     * @return the value of crm_attachment.value2
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public String getValue2() {
        return value2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_attachment.value2
     *
     * @param value2 the value for crm_attachment.value2
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public void setValue2(String value2) {
        this.value2 = value2 == null ? null : value2.trim();
    }
}