package com.sh.drools.dal.model;

import java.util.Date;
import java.util.List;

public class Member {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_member.ID
     *
     * @mbggenerated Wed Jun 19 10:21:34 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_member.PASSWORD
     *
     * @mbggenerated Wed Jun 19 10:21:34 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_member.USER_NAME
     *
     * @mbggenerated Wed Jun 19 10:21:34 CST 2019
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_member.STATUS
     *
     * @mbggenerated Wed Jun 19 10:21:34 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_member.EMAIL
     *
     * @mbggenerated Wed Jun 19 10:21:34 CST 2019
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_member.AVATAR
     *
     * @mbggenerated Wed Jun 19 10:21:34 CST 2019
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_member.GENDER
     *
     * @mbggenerated Wed Jun 19 10:21:34 CST 2019
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_member.HIREDATE
     *
     * @mbggenerated Wed Jun 19 10:21:34 CST 2019
     */
    private Date hiredate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_member.REAL_NAME
     *
     * @mbggenerated Wed Jun 19 10:21:34 CST 2019
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_member.TELEPHONE
     *
     * @mbggenerated Wed Jun 19 10:21:34 CST 2019
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_member.value1
     *
     * @mbggenerated Wed Jun 19 10:21:34 CST 2019
     */
    private String value1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_member.value2
     *
     * @mbggenerated Wed Jun 19 10:21:34 CST 2019
     */
    private String value2;

    private List<Role> roles;

    public List<Role> getRoles() {
        return roles;
    }

    public void setRoles(List<Role> roles) {
        this.roles = roles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_member.ID
     *
     * @return the value of crm_member.ID
     *
     * @mbggenerated Wed Jun 19 10:21:34 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_member.ID
     *
     * @param id the value for crm_member.ID
     *
     * @mbggenerated Wed Jun 19 10:21:34 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_member.PASSWORD
     *
     * @return the value of crm_member.PASSWORD
     *
     * @mbggenerated Wed Jun 19 10:21:34 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_member.PASSWORD
     *
     * @param password the value for crm_member.PASSWORD
     *
     * @mbggenerated Wed Jun 19 10:21:34 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_member.USER_NAME
     *
     * @return the value of crm_member.USER_NAME
     *
     * @mbggenerated Wed Jun 19 10:21:34 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_member.USER_NAME
     *
     * @param userName the value for crm_member.USER_NAME
     *
     * @mbggenerated Wed Jun 19 10:21:34 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_member.STATUS
     *
     * @return the value of crm_member.STATUS
     *
     * @mbggenerated Wed Jun 19 10:21:34 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_member.STATUS
     *
     * @param status the value for crm_member.STATUS
     *
     * @mbggenerated Wed Jun 19 10:21:34 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_member.EMAIL
     *
     * @return the value of crm_member.EMAIL
     *
     * @mbggenerated Wed Jun 19 10:21:34 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_member.EMAIL
     *
     * @param email the value for crm_member.EMAIL
     *
     * @mbggenerated Wed Jun 19 10:21:34 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_member.AVATAR
     *
     * @return the value of crm_member.AVATAR
     *
     * @mbggenerated Wed Jun 19 10:21:34 CST 2019
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_member.AVATAR
     *
     * @param avatar the value for crm_member.AVATAR
     *
     * @mbggenerated Wed Jun 19 10:21:34 CST 2019
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_member.GENDER
     *
     * @return the value of crm_member.GENDER
     *
     * @mbggenerated Wed Jun 19 10:21:34 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_member.GENDER
     *
     * @param gender the value for crm_member.GENDER
     *
     * @mbggenerated Wed Jun 19 10:21:34 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_member.HIREDATE
     *
     * @return the value of crm_member.HIREDATE
     *
     * @mbggenerated Wed Jun 19 10:21:34 CST 2019
     */
    public Date getHiredate() {
        return hiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_member.HIREDATE
     *
     * @param hiredate the value for crm_member.HIREDATE
     *
     * @mbggenerated Wed Jun 19 10:21:34 CST 2019
     */
    public void setHiredate(Date hiredate) {
        this.hiredate = hiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_member.REAL_NAME
     *
     * @return the value of crm_member.REAL_NAME
     *
     * @mbggenerated Wed Jun 19 10:21:34 CST 2019
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_member.REAL_NAME
     *
     * @param realName the value for crm_member.REAL_NAME
     *
     * @mbggenerated Wed Jun 19 10:21:34 CST 2019
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_member.TELEPHONE
     *
     * @return the value of crm_member.TELEPHONE
     *
     * @mbggenerated Wed Jun 19 10:21:34 CST 2019
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_member.TELEPHONE
     *
     * @param telephone the value for crm_member.TELEPHONE
     *
     * @mbggenerated Wed Jun 19 10:21:34 CST 2019
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_member.value1
     *
     * @return the value of crm_member.value1
     *
     * @mbggenerated Wed Jun 19 10:21:34 CST 2019
     */
    public String getValue1() {
        return value1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_member.value1
     *
     * @param value1 the value for crm_member.value1
     *
     * @mbggenerated Wed Jun 19 10:21:34 CST 2019
     */
    public void setValue1(String value1) {
        this.value1 = value1 == null ? null : value1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_member.value2
     *
     * @return the value of crm_member.value2
     *
     * @mbggenerated Wed Jun 19 10:21:34 CST 2019
     */
    public String getValue2() {
        return value2;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_member.value2
     *
     * @param value2 the value for crm_member.value2
     *
     * @mbggenerated Wed Jun 19 10:21:34 CST 2019
     */
    public void setValue2(String value2) {
        this.value2 = value2 == null ? null : value2.trim();
    }
}