package com.sh.drools.dal.model;

public class Resource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_resource.ID
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_resource.FUN_URLS
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    private String funUrls;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_resource.MENU_URL
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    private String menuUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_resource.RES_KEY
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    private String resKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_resource.RES_NAME
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    private String resName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_resource.RES_TYPE
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    private String resType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_resource.STATUS
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_resource.WEIGHT
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    private Integer weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_resource.PARENT_ID
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_resource.value1
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    private String value1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_resource.value2
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    private String value2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_resource.ID
     *
     * @return the value of crm_resource.ID
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_resource.ID
     *
     * @param id the value for crm_resource.ID
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_resource.FUN_URLS
     *
     * @return the value of crm_resource.FUN_URLS
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public String getFunUrls() {
        return funUrls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_resource.FUN_URLS
     *
     * @param funUrls the value for crm_resource.FUN_URLS
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public void setFunUrls(String funUrls) {
        this.funUrls = funUrls == null ? null : funUrls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_resource.MENU_URL
     *
     * @return the value of crm_resource.MENU_URL
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_resource.MENU_URL
     *
     * @param menuUrl the value for crm_resource.MENU_URL
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl == null ? null : menuUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_resource.RES_KEY
     *
     * @return the value of crm_resource.RES_KEY
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public String getResKey() {
        return resKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_resource.RES_KEY
     *
     * @param resKey the value for crm_resource.RES_KEY
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public void setResKey(String resKey) {
        this.resKey = resKey == null ? null : resKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_resource.RES_NAME
     *
     * @return the value of crm_resource.RES_NAME
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public String getResName() {
        return resName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_resource.RES_NAME
     *
     * @param resName the value for crm_resource.RES_NAME
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public void setResName(String resName) {
        this.resName = resName == null ? null : resName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_resource.RES_TYPE
     *
     * @return the value of crm_resource.RES_TYPE
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public String getResType() {
        return resType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_resource.RES_TYPE
     *
     * @param resType the value for crm_resource.RES_TYPE
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public void setResType(String resType) {
        this.resType = resType == null ? null : resType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_resource.STATUS
     *
     * @return the value of crm_resource.STATUS
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_resource.STATUS
     *
     * @param status the value for crm_resource.STATUS
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_resource.WEIGHT
     *
     * @return the value of crm_resource.WEIGHT
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_resource.WEIGHT
     *
     * @param weight the value for crm_resource.WEIGHT
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_resource.PARENT_ID
     *
     * @return the value of crm_resource.PARENT_ID
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_resource.PARENT_ID
     *
     * @param parentId the value for crm_resource.PARENT_ID
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_resource.value1
     *
     * @return the value of crm_resource.value1
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public String getValue1() {
        return value1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_resource.value1
     *
     * @param value1 the value for crm_resource.value1
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public void setValue1(String value1) {
        this.value1 = value1 == null ? null : value1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_resource.value2
     *
     * @return the value of crm_resource.value2
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public String getValue2() {
        return value2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_resource.value2
     *
     * @param value2 the value for crm_resource.value2
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public void setValue2(String value2) {
        this.value2 = value2 == null ? null : value2.trim();
    }
}