package com.sh.drools.dal.model;

public class RoleResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_role_resource.ID
     *
     * @mbggenerated Fri Jun 14 18:00:14 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_role_resource.ROLE_ID
     *
     * @mbggenerated Fri Jun 14 18:00:14 CST 2019
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_role_resource.RESOURCE_ID
     *
     * @mbggenerated Fri Jun 14 18:00:14 CST 2019
     */
    private Integer resourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_role_resource.value1
     *
     * @mbggenerated Fri Jun 14 18:00:14 CST 2019
     */
    private String value1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_role_resource.value2
     *
     * @mbggenerated Fri Jun 14 18:00:14 CST 2019
     */
    private String value2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_role_resource.ID
     *
     * @return the value of crm_role_resource.ID
     *
     * @mbggenerated Fri Jun 14 18:00:14 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_role_resource.ID
     *
     * @param id the value for crm_role_resource.ID
     *
     * @mbggenerated Fri Jun 14 18:00:14 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_role_resource.ROLE_ID
     *
     * @return the value of crm_role_resource.ROLE_ID
     *
     * @mbggenerated Fri Jun 14 18:00:14 CST 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_role_resource.ROLE_ID
     *
     * @param roleId the value for crm_role_resource.ROLE_ID
     *
     * @mbggenerated Fri Jun 14 18:00:14 CST 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_role_resource.RESOURCE_ID
     *
     * @return the value of crm_role_resource.RESOURCE_ID
     *
     * @mbggenerated Fri Jun 14 18:00:14 CST 2019
     */
    public Integer getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_role_resource.RESOURCE_ID
     *
     * @param resourceId the value for crm_role_resource.RESOURCE_ID
     *
     * @mbggenerated Fri Jun 14 18:00:14 CST 2019
     */
    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_role_resource.value1
     *
     * @return the value of crm_role_resource.value1
     *
     * @mbggenerated Fri Jun 14 18:00:14 CST 2019
     */
    public String getValue1() {
        return value1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_role_resource.value1
     *
     * @param value1 the value for crm_role_resource.value1
     *
     * @mbggenerated Fri Jun 14 18:00:14 CST 2019
     */
    public void setValue1(String value1) {
        this.value1 = value1 == null ? null : value1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_role_resource.value2
     *
     * @return the value of crm_role_resource.value2
     *
     * @mbggenerated Fri Jun 14 18:00:14 CST 2019
     */
    public String getValue2() {
        return value2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_role_resource.value2
     *
     * @param value2 the value for crm_role_resource.value2
     *
     * @mbggenerated Fri Jun 14 18:00:14 CST 2019
     */
    public void setValue2(String value2) {
        this.value2 = value2 == null ? null : value2.trim();
    }
}