package com.sh.drools.dal.model;

public class RuleInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_info.rule_id
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    private String ruleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_info.rule_name
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    private String ruleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_info.rule_condition
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    private String ruleCondition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_info.status
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_info.rule_id
     *
     * @return the value of rule_info.rule_id
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public String getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_info.rule_id
     *
     * @param ruleId the value for rule_info.rule_id
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public void setRuleId(String ruleId) {
        this.ruleId = ruleId == null ? null : ruleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_info.rule_name
     *
     * @return the value of rule_info.rule_name
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public String getRuleName() {
        return ruleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_info.rule_name
     *
     * @param ruleName the value for rule_info.rule_name
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public void setRuleName(String ruleName) {
        this.ruleName = ruleName == null ? null : ruleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_info.rule_condition
     *
     * @return the value of rule_info.rule_condition
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public String getRuleCondition() {
        return ruleCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_info.rule_condition
     *
     * @param ruleCondition the value for rule_info.rule_condition
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public void setRuleCondition(String ruleCondition) {
        this.ruleCondition = ruleCondition == null ? null : ruleCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_info.status
     *
     * @return the value of rule_info.status
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_info.status
     *
     * @param status the value for rule_info.status
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}