package com.sh.drools.dal.mapper;

import com.sh.drools.dal.model.Member;

public interface MemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_member
     *
     * @mbggenerated Fri Jun 14 18:00:14 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_member
     *
     * @mbggenerated Fri Jun 14 18:00:14 CST 2019
     */
    int insert(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_member
     *
     * @mbggenerated Fri Jun 14 18:00:14 CST 2019
     */
    int insertSelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_member
     *
     * @mbggenerated Fri Jun 14 18:00:14 CST 2019
     */
    Member selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_member
     *
     * @mbggenerated Fri Jun 14 18:00:14 CST 2019
     */
    int updateByPrimaryKeySelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_member
     *
     * @mbggenerated Fri Jun 14 18:00:14 CST 2019
     */
    int updateByPrimaryKey(Member record);
}