package com.sh.drools.dal.mapper;

import com.sh.drools.dal.model.Resource;

public interface ResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_resource
     *
     * @mbggenerated Fri Jun 14 18:00:14 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_resource
     *
     * @mbggenerated Fri Jun 14 18:00:14 CST 2019
     */
    int insert(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_resource
     *
     * @mbggenerated Fri Jun 14 18:00:14 CST 2019
     */
    int insertSelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_resource
     *
     * @mbggenerated Fri Jun 14 18:00:14 CST 2019
     */
    Resource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_resource
     *
     * @mbggenerated Fri Jun 14 18:00:14 CST 2019
     */
    int updateByPrimaryKeySelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_resource
     *
     * @mbggenerated Fri Jun 14 18:00:14 CST 2019
     */
    int updateByPrimaryKey(Resource record);
}