package com.sh.drools.dal.mapper;

import com.sh.drools.dal.model.RoleResource;

public interface RoleResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_role_resource
     *
     * @mbggenerated Fri Jun 14 18:00:14 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_role_resource
     *
     * @mbggenerated Fri Jun 14 18:00:14 CST 2019
     */
    int insert(RoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_role_resource
     *
     * @mbggenerated Fri Jun 14 18:00:14 CST 2019
     */
    int insertSelective(RoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_role_resource
     *
     * @mbggenerated Fri Jun 14 18:00:14 CST 2019
     */
    RoleResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_role_resource
     *
     * @mbggenerated Fri Jun 14 18:00:14 CST 2019
     */
    int updateByPrimaryKeySelective(RoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_role_resource
     *
     * @mbggenerated Fri Jun 14 18:00:14 CST 2019
     */
    int updateByPrimaryKey(RoleResource record);
}