package com.sh.drools.dal.mapper;

import com.sh.drools.dal.model.Role;

import java.util.List;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_role
     *
     * @mbggenerated Wed Jun 19 11:52:41 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_role
     *
     * @mbggenerated Wed Jun 19 11:52:41 CST 2019
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_role
     *
     * @mbggenerated Wed Jun 19 11:52:41 CST 2019
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_role
     *
     * @mbggenerated Wed Jun 19 11:52:41 CST 2019
     */
    Role selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_role
     *
     * @mbggenerated Wed Jun 19 11:52:41 CST 2019
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_role
     *
     * @mbggenerated Wed Jun 19 11:52:41 CST 2019
     */
    int updateByPrimaryKey(Role record);

    List<Role> findByStatus(boolean b);

    List<Role> findAll();
}