package com.sh.drools.dal.mapper;

import com.sh.drools.dal.model.RuleInfo;
import com.sh.drools.dal.model.RuleInfoWithBLOBs;

import java.util.List;

public interface RuleInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_info
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    int deleteByPrimaryKey(String ruleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_info
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    int insert(RuleInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_info
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    int insertSelective(RuleInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_info
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    RuleInfoWithBLOBs selectByPrimaryKey(String ruleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_info
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    int updateByPrimaryKeySelective(RuleInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_info
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(RuleInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_info
     *
     * @mbggenerated Mon Jun 17 16:09:28 CST 2019
     */
    int updateByPrimaryKey(RuleInfo record);

    List<RuleInfoWithBLOBs> selectByStatus(String status);
}